name: 'Vault Secrets'
description: 'A Github Action that allows you to consume the v2 K/V backend of HashiCorp Vault as secure environment variables'
inputs:
  url:
    description: 'The URL for the vault endpoint'
    required: true
  token:
    description: 'The Vault Token to be used to authenticate with Vault'
    required: true
  secrets:
    description: 'A semicolon-separated list of secrets to retrieve. These will automatically be converted to environmental variable keys. See README for more details'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'unlock'
  color: 'gray-dark'